

DROP TABLE IF EXISTS menu_orders CASCADE;
CREATE TABLE menu_orders (
  id SERIAL PRIMARY KEY NOT NULL,
  menu_id INTEGER REFERENCES menu(id) NOT NULL ON DELETE CASCADE,
  order_id INTEGER REFERENCES order(id) NOT NULL ON DELETE CASCADE,
  qty INTEGER
);
